# -*- coding: utf-8 -*-
"""przygotowanie_danych.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWpgypeQ-xiwFdna6fl88zE87fuCGHAh
"""

!pip install mne

import pandas  as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import mne
import sklearn

#---------------------------------------------Wczytywanie danych--------------------------

NICK_BADANEGO = "abc"
CSV_EVENTY = "abc_EEGBasedVisualRecall_Events_Rep1_2026-05-27_11-04-56.csv"

raw_data = mne.io.read_raw_edf(f"{NICK_BADANEGO}_raw.edf", preload=True, infer_types=True) # załaduj do pamięci, typ EEG do znanych kanałów
print("\n#############################################\n")
print(raw_data) #Informacje o kanałach i objekcie
print("\n#############################################\n")
print(raw_data.info) #Informacje o kanałach i objekcie
print("\n#############################################\n")
print(raw_data.describe()) #Informacje o kanałach i objekcie
print("\n#############################################\n")

#----------------------------Sprawdzenie bieżących nazw kanałów---------------------------
print(raw_data.ch_names)

#----------------------------Zmiana nazw kanałów------------------------------------------
newNames = { ch:ch.split('-')[0].strip() for ch in raw_data.ch_names}
raw_data.rename_channels(newNames)

#----------------------------Zmiana typów kanałów-----------------------------------------
ch_types = {}
for ch in raw_data.ch_names:
    if ch in ['X1:', 'X2:', 'X3:', 'CM']:
        ch_types[ch] = 'misc'
    elif ch in ['Trigger', 'Event']:
        ch_types[ch] = 'stim'
    elif ch[:3] == "Imp":
        raw_data.drop_channels([ch])
    else:
        ch_types[ch] = 'eeg'
raw_data.set_channel_types(ch_types)

#----------------------------Zmiana montażu i referencji-----------------------------------
montage = mne.channels.make_standard_montage('standard_1020')
raw_data.set_montage(montage, on_missing='ignore')

#----------------------------Wyświetlenie układu elektrod na obrazku-----------------------
raw_data.plot_sensors(kind='topomap', show_names=True);