# -*- coding: utf-8 -*-
"""ModelTrainingCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EUPPPynnJyOsY_xRekoVPA-ZqjHc2UTB
"""

import gc
import os
import time
import random
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sys import getsizeof
import tensorflow as tf
print(tf.__version__)
from tensorflow.keras import metrics
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers, callbacks
from tensorflow.keras.models import Sequential, Model
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from tensorflow.keras import layers, models
from sklearn.preprocessing import LabelEncoder

#Definicje i założenia
nicki_badanych = ["abc", "Bear", "fghx", "jt", "mi2", "miguel", "mole", "Reshi", "sapling"]

przedrostek_pliku_danych = "plikWynikowy"
przedrostek_pliku_etykiet = "plikWynikowyET"
przedrostek_pliku_stat = "paramerty_"
nazwa_pliku = "_Dane32Przetworzone"
oznaczenie = "AVG"
etapy_pliku = ["TRAIN" , "TEST"]

przebiegi = [[0,1],[2,3], [4,5],[6], [7,8]]
przebieg_testowy = len(przebiegi)-1

sciezka_wag = "dogotowywane.weights.h5"

#KONFIGUROWWALNE PARAMETRYY
dane_wieloplikowe = True
nr_przebiegu = 3 #  0-dane 0-3    |   1-> dane 4-6  |  2 -> dane tesowe , przebieg testowy
etap_pliku = etapy_pliku[0]
# 0 trenuj i zapisz niedogotowany model
# 1 trenuj i zapisz dogotowany model
# 2 nie trenuj, tylko przetestuj i zrob wykresy

#Łączenie z dyskiem
#from google.colab import drive
#drive.mount('/content/drive')
#dataSourcePath = '/content/drive/MyDrive/BIAI/'

dataSourcePath = 'data2/'

X = []
y_txt = []

if dane_wieloplikowe:
  parametry_stat = np.load(dataSourcePath+przedrostek_pliku_stat+etap_pliku+".npy")
  srednia = parametry_stat[0]
  odch_std = parametry_stat[1]

  for nr_plikow in przebiegi[nr_przebiegu]:
    nx = np.load(dataSourcePath+przedrostek_pliku_danych +str(nr_plikow)+"_"+etap_pliku+nazwa_pliku+oznaczenie+".npy", mmap_mode='r')
    ey = np.load(dataSourcePath+przedrostek_pliku_etykiet+str(nr_plikow)+"_"+etap_pliku+nazwa_pliku+oznaczenie+".npy", mmap_mode='r')

    nx = (nx-srednia)/odch_std  #PROBLEMY Z PAMIĘCCIĄ KOPIOWANIE TABLIC UKRYTE W SKRYPCIE

    X.append(nx)
    y_txt.append(ey)

    del nx
    del ey
    gc.collect()

  X = np.concatenate(X)
  y_txt = np.concatenate(y_txt)

  X = np.transpose(X, (0,2,3,1))

else:
  X = np.load(dataSourcePath+"abc_Dane32PrzetworzoneAVGlog.npy")
  y_txt = np.load(dataSourcePath+"abc_EtykietyDanychlog.npy", allow_pickle=True)
  X = np.transpose(X, (0,2,3,1))

input_shape = X.shape[1:]   # Wymiary pojedynczego obrazu

print(X.shape)
print(y_txt.shape)
print(input_shape)

labelEnc = LabelEncoder()
y = labelEnc.fit_transform(y_txt)
l_klas = len(labelEnc.classes_)
print(labelEnc.classes_)

if not dane_wieloplikowe:
  X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
  X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size=0.25, random_state=42)

  #Normalizacja - standaryzacja (Z-score)
  srednia = np.mean(X_train, axis=(0,1,2), keepdims=True) # 0-epoka, 1-czestotliwosc, 2-czas <-Do usrednienia     3-kanal
  std = np.std(X_train, axis=(0,1,2), keepdims=True )

  print(srednia.shape)
  print("Srednie dla 21 kanalow: \n")
  print(srednia[0][0][0])

  X_train= (X_train - srednia)/std
  X_validate = (X_validate - srednia)/std
  X_test = (X_test - srednia)/std
else:
  if nr_przebiegu == przebieg_testowy:
    X_test = X
    y_test = y

model = models.Sequential()
model.add(layers.Conv2D(32, (1, 10), activation=None, padding='same', input_shape=input_shape))
model.add(layers.BatchNormalization())#  #
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D((2,2)))#   #
model.add(layers.Conv2D(64, (3,1), activation=None, padding='same'))
model.add(layers.BatchNormalization())#  #
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D((2,3)))
model.add(layers.Dropout(0.2)) # (anti-overfitting)
model.add(layers.DepthwiseConv2D(64, (3,3), activation=None, depth_multiplier=2, padding='same'))
model.add(layers.BatchNormalization())#  #
model.add(layers.Activation('relu'))
model.add(layers.DepthwiseConv2D(64, (2,2), activation=None, padding='same'))
model.add(layers.BatchNormalization())#  #
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D((2,2)))#   #

model.add(layers.Flatten())
  #model.add(layers.GlobalAveragePooling2D())
model.add(layers.Dense(128, activation=None))
  #model.add(layers.BatchNormalization())
model.add(layers.Activation('relu'))
model.add(layers.Dropout(0.3)) # (anti-overfitting)
model.add(layers.Dense(l_klas, activation='softmax'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(optimizer = optimizer , loss = 'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'],#, metrics.Precision(), metrics.Recall(), metrics.AUC()],
              jit_compile=False)
model.summary()

ReduceLROnPlateau_callback = callbacks.ReduceLROnPlateau(
      monitor='val_accuracy',
      patience = 5,
      verbose=1,
      factor=0.3,
      min_lr=0.0000001)

EarlyStopping_callback = callbacks.EarlyStopping(
      monitor='val_loss',
      patience=10,
      start_from_epoch = 15,
      restore_best_weights=True,
      verbose=0,
      mode='min')

if nr_przebiegu != 0 and dane_wieloplikowe:
    model.load_weights(dataSourcePath+sciezka_wag)
    print("Poprwanie wczytano wagi!")
else:
    print("Utworzono nowy model!")

epochs = 70
batch_size=32  #16 # im mniejsza, tym większa dokładność, ale i więcej czasu

if dane_wieloplikowe:
  print("Poczatek treningu")
  hist = model.fit(
      x=X,
      y=y,
      batch_size=batch_size,
      epochs=epochs,
      verbose=1,
      callbacks=[ReduceLROnPlateau_callback, EarlyStopping_callback],
      #callbacks=[ReduceLROnPlateau_callback],
      shuffle=True
  )
  model.save_weights(dataSourcePath+sciezka_wag)
  print("Trening zakonczony, model zapisany")
else:
  print("Poczatek treningu (bez walidacji)")
  hist = model.fit(
      x=X_train,
      y=y_train,
      batch_size=batch_size,
      epochs=epochs,
      verbose=1,
      callbacks=[ReduceLROnPlateau_callback, EarlyStopping_callback],
      #callbacks=[ReduceLROnPlateau_callback],
      validation_data=(X_validate, y_validate),
      shuffle=True
  )

if nr_przebiegu == przebieg_testowy or not dane_wieloplikowe:
  test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
  print(f"Skuteczność na danych testowych: {test_acc*100:.2f}%")

if nr_przebiegu == przebieg_testowy or not dane_wieloplikowe:
  y_predicted = model.predict(X_test)
  y_p_argmax = np.argmax(y_predicted, axis=1)
  #y_test_argmax = np.argmax(y_test.to_numpy(), axis=1)
  categories=["abstract","airplane","apple","banana","bird","boat","car","dog","person","train","zebra"]

  print(classification_report(y_test,y_p_argmax))
  matrix = confusion_matrix(y_test, y_p_argmax)

  disp = ConfusionMatrixDisplay(matrix, display_labels=categories)
  fig, ax = plt.subplots(figsize=(12,12))
  disp.plot(ax=ax, cmap="plasma") #viridis , plasma
  plt.xticks(rotation=45, ha='right')
  plt.show()
  plt.close()

if nr_przebiegu == przebieg_testowy or not dane_wieloplikowe:
  wyk, (os1,os2) = plt.subplots(1,2, figsize=(20,5))
  os1.plot(hist.history['loss'],label='Strata',color='#AA0000',linewidth=2)
  os1.plot(hist.history['val_loss'],label='StrataVal',color='#FFAA00',linewidth=2)
  os1.set_title('Strata')
  os1.set_xlabel('Epoka',fontsize=10)
  os1.set_ylabel('Wartosc',fontsize=10)
  os1.grid(True,linestyle='--',alpha=0.6)
  os1.legend(fontsize=10)

  os2.plot(hist.history['accuracy'],label='Celność',color='#00AA00',linewidth=2)
  os2.plot(hist.history['val_accuracy'],label='CelnośćVal',color='#AAFF00',linewidth=2)
  os2.set_title('Celnosc')
  os2.set_xlabel('Epoka',fontsize=10)
  os2.set_ylabel('Wartosc',fontsize=10)
  os2.grid(True,linestyle='--',alpha=0.6)
  os2.legend(fontsize=10)

#model.save(dataSourcePath + "Najlepszy3-09-0_44" + ".keras")
#zaladowany = keras.models.load_model(dataSourcePath+nazwa+".keras")